### PR TITLE
Styling suggestion with Skeleton

### PR DESCRIPTION
**Pull request by Max-le**
Hi frog23, 

Hereby I propose to use the css framework [Skeleton](http://getskeleton.com/) for a slight improvement of design.

So I added skeleton.css, linked it to index.html and review.html, and removed the Helvetica font on tsm.css to apply Skeleton's font. 
Finally I changed the a tag's color to red.

See the two screenshots below for an overview. 

Screenshot 2022-06-08 at 19 04 40

Screenshot 2022-06-08 at 19 04 35
.

Let me know if you like it !

### CODE REVIEW

**Comment by Plushb9rry** [comment]
That looks awesome, i was also trying to improve the page few days ago, but I didn't complete it well.

image

**Comment by Plushb9rry** [comment]
> So I added skeleton.css, linked it to index.html and review.html, and removed the Helvetica font on tsm.css to apply Skeleton's font. Finally I changed the a tag's color to red.

These fonts look a lot familiar to 'Railway' by google

**Comment by Max-le** [comment]
Thanks, your idea looks cool as well ( and yes, you recognized the font correctly )
:)

**Comment by frog23** [comment]
Hey Max-le,
thank you for your PR. The site looks a lot better now. Sorry, that it took me so long to respond. It has been a busy couple of weeks and I didn't have time to properly review the PR.
Thanks again and sorry for the wait.
Cheers, Frog23

**Comment by Max-le** [comment]
I prefer the first one, with his face ! 🙂

**Comment by frog23** [comment]
I added my thoughts on the matter here: https://github.com/frog23/TomScottMap/pull/50#issuecomment-1179729938

**Pull request merged**
