### PR TITLE
new video is here! i hope

### PR DESCRIPTION
**Pull request by Plushb9rry**
i am correct about location

### CODE REVIEW

**Comment by frog23** [comment]
thanks for looking up the coordinates.

**Comment by Plushb9rry** [comment]
my pleasure , by the way i am wondering how new entry is made when the new
video is uploaded , is it like any API thingy working , how it works?
thanks !

**Comment by frog23** [comment]
I wrote a little script for it that runs on the server and is called via crontab every couple of minutes to check for new videos. I just published it in it's own repo: [TomScottMap-updater](https://github.com/frog23/TomScottMap-updater). It is written in bash and php, in true [Art of the Bodge](https://www.youtube.com/watch?v=lIFE7h3m40U)-fashion. The script then does the commit and push to the repo, and a post commit hook, then pulls the new code to the web server.

**Comment by Plushb9rry** [comment]
wow nice to know how that works , Thank you!

**Pull request merged**
